name: Tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches-ignore: []

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python: [3.6,3.7,3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.X
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: conda
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies conda
      run: |
        conda install -c conda-forge mamba --quiet
        #conda list | grep ruamel
        #conda update ruamel_yaml
    - name: Install sequana with pip
      run: |
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
        pip install .
    - name: Test with pytest
      run: |
        pytest --cov-report term --cov=sequana_sphinxext
    - name: coveralls
      run: |
        coveralls --service=github
